pub const FACTORY_REFINE_SLOTS: usize = 2;
pub const FACTORY_REFINE_TIME: f32 = 10.0;
pub const FACTORY_ENERGY_PER_REFINE: f32 = 2.0;
pub const FACTORY_IDLE_ENERGY_PER_SEC: f32 = 1.0;
pub const FACTORY_STORAGE_CAPACITY: f32 = 300.0;
pub const FACTORY_ENERGY_CAPACITY: f32 = 80.0;
pub const FACTORY_INITIAL_ENERGY: f32 = 40.0;
pub const FACTORY_SOLAR_MAX_ENERGY_PER_LEVEL: f32 = 10.0;
pub const SOLAR_ARRAY_LOCAL_MAX_ENERGY_PER_LEVEL: f32 = 3.0;

pub const SOLAR_BASE_GEN: f32 = 7.0;
pub const BASE_ENERGY_CAP: f32 = 100.0;
pub const ENERGY_PER_SOLAR: f32 = 25.0;
pub const FACTORY_SOLAR_BASE_REGEN: f32 = 1.25;
pub const FACTORY_SOLAR_REGEN_PER_LEVEL: f32 = 0.5;
pub const SOLAR_ARRAY_LOCAL_REGEN_PER_LEVEL: f32 = 0.25;

pub const UPGRADE_GROWTH: f32 = 1.35;

pub const DRONE_MAX_BATTERY: f32 = 24.0;
pub const DRONE_ENERGY_COST: f32 = 0.9;
pub const DRONE_MAX_CARGO: f32 = 10.0;

pub const DRONE_STATE_IDLE: f32 = 0.0;
pub const DRONE_STATE_TO_ASTEROID: f32 = 1.0;
pub const DRONE_STATE_MINING: f32 = 2.0;
pub const DRONE_STATE_RETURNING: f32 = 3.0;
pub const DRONE_STATE_UNLOADING: f32 = 4.0;
